### PR TITLE
Fix service name annotation for emissary ingress

### PR DESCRIPTION
**Pull request by oleksii-delphai**

### CODE REVIEW

**Comment by oleksii-delphai** [comment]
`external-dns` continues spamming with messages `level=error msg="services \"ambassador\" not found"`
It’s likely because it tries to find `ambassador` service which is in annotations but it should look at `emissary-ingress`

**Comment by oleksii-delphai** [comment]
I might miss some of them 
Will recheck once more

**Review by anton-delphai — CHANGES_REQUESTED** [review]
Most likely we don't need that

**Comment by anton-delphai** [comment]
This is `delphai-ui/delphai-ui-v1-5377-notifications-http`

**Pull request closed without merging**
