### PR TITLE
DEVOPS-274 Remove unused charts

### PR DESCRIPTION
**Pull request by anton-delphai**

### CODE REVIEW

**Comment by tadeusz-delphai** [comment]
How did you determine which ones are unused?

**Review by malek-delphai — APPROVED** [review]

**Comment by malek-delphai** [comment]
Does it close https://github.com/delphai/helm-charts/pull/60?

**Comment by anton-delphai** [comment]
```
git clone *
grep -rl FOO
```

**Comment by anton-delphai** [comment]
@tadeusz-delphai 
```
git clone *
grep -rl FOO
```

**Review by malek-delphai — APPROVED** [review]

**Pull request merged**
